In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

import matplotlib.pyplot as plt

%matplotlib inline

In [ ]:


data = pd.read_csv('/content/drive/MyDrive/content/voice.csv')
data.head()



meanfreq        sd    median       Q25       Q75       IQR       skew  \
0  0.059781  0.064241  0.032027  0.015071  0.090193  0.075122  12.863462   
1  0.066009  0.067310  0.040229  0.019414  0.092666  0.073252  22.423285   
2  0.077316  0.083829  0.036718  0.008701  0.131908  0.123207  30.757155   
3  0.151228  0.072111  0.158011  0.096582  0.207955  0.111374   1.232831   
4  0.135120  0.079146  0.124656  0.078720  0.206045  0.127325   1.101174   

          kurt    sp.ent       sfm  ...  centroid   meanfun    minfun  \
0   274.402906  0.893369  0.491918  ...  0.059781  0.084279  0.015702   
1   634.613855  0.892193  0.513724  ...  0.066009  0.107937  0.015826   
2  1024.927705  0.846389  0.478905  ...  0.077316  0.098706  0.015656   
3     4.177296  0.963322  0.727232  ...  0.151228  0.088965  0.017798   
4     4.333713  0.971955  0.783568  ...  0.135120  0.106398  0.016931   

     maxfun   meandom    mindom    maxdom   dfrange   modindx  label  
0  0.275862  0.007812  0.007812  0.007812  0.000000  0.000000   male  
1  0.250000  0.009014  0.007812  0.054688  0.046875  0.052632   male  
2  0.271186  0.007990  0.007812  0.015625  0.007812  0.046512   male  
3  0.250000  0.201497  0.007812  0.562500  0.554688  0.247119   male  
4  0.266667  0.712812  0.007812  5.484375  5.476562  0.208274   male  

[5 rows x 21 columns]

In [ ]:
data.corr()

meanfreq        sd    median       Q25       Q75       IQR  \
meanfreq  1.000000 -0.739039  0.925445  0.911416  0.740997 -0.627605   
sd       -0.739039  1.000000 -0.562603 -0.846931 -0.161076  0.874660   
median    0.925445 -0.562603  1.000000  0.774922  0.731849 -0.477352   
Q25       0.911416 -0.846931  0.774922  1.000000  0.477140 -0.874189   
Q75       0.740997 -0.161076  0.731849  0.477140  1.000000  0.009636   
IQR      -0.627605  0.874660 -0.477352 -0.874189  0.009636  1.000000   
skew     -0.322327  0.314597 -0.257407 -0.319475 -0.206339  0.249497   
kurt     -0.316036  0.346241 -0.243382 -0.350182 -0.148881  0.316185   
sp.ent   -0.601203  0.716620 -0.502005 -0.648126 -0.174905  0.640813   
sfm      -0.784332  0.838086 -0.661690 -0.766875 -0.378198  0.663601   
mode      0.687715 -0.529150  0.677433  0.591277  0.486857 -0.403764   
centroid  1.000000 -0.739039  0.925445  0.911416  0.740997 -0.627605   
meanfun   0.460844 -0.466281  0.414909  0.545035  0.155091 -0.534462   
minfun    0.383937 -0.345609  0.337602  0.320994  0.258002 -0.222680   
maxfun    0.274004 -0.129662  0.251328  0.199841  0.285584 -0.069588   
meandom   0.536666 -0.482726  0.455943  0.467403  0.359181 -0.333362   
mindom    0.229261 -0.357667  0.191169  0.302255 -0.023750 -0.357037   
maxdom    0.519528 -0.482278  0.438919  0.459683  0.335114 -0.337877   
dfrange   0.515570 -0.475999  0.435621  0.454394  0.335648 -0.331563   
modindx  -0.216979  0.122660 -0.213298 -0.141377 -0.216475  0.041252   

              skew      kurt    sp.ent       sfm      mode  centroid  \
meanfreq -0.322327 -0.316036 -0.601203 -0.784332  0.687715  1.000000   
sd        0.314597  0.346241  0.716620  0.838086 -0.529150 -0.739039   
median   -0.257407 -0.243382 -0.502005 -0.661690  0.677433  0.925445   
Q25      -0.319475 -0.350182 -0.648126 -0.766875  0.591277  0.911416   
Q75      -0.206339 -0.148881 -0.174905 -0.378198  0.486857  0.740997   
IQR       0.249497  0.316185  0.640813  0.663601 -0.403764 -0.627605   
skew      1.000000  0.977020 -0.195459  0.079694 -0.434859 -0.322327   
kurt      0.977020  1.000000 -0.127644  0.109884 -0.406722 -0.316036   
sp.ent   -0.195459 -0.127644  1.000000  0.866411 -0.325298 -0.601203   
sfm       0.079694  0.109884  0.866411  1.000000 -0.485913 -0.784332   
mode     -0.434859 -0.406722 -0.325298 -0.485913  1.000000  0.687715   
centroid -0.322327 -0.316036 -0.601203 -0.784332  0.687715  1.000000   
meanfun  -0.167668 -0.194560 -0.513194 -0.421066  0.324771  0.460844   
minfun   -0.216954 -0.203201 -0.305826 -0.362100  0.385467  0.383937   
maxfun   -0.080861 -0.045667 -0.120738 -0.192369  0.172329  0.274004   
meandom  -0.336848 -0.303234 -0.293562 -0.428442  0.491479  0.536666   
mindom   -0.061608 -0.103313 -0.294869 -0.289593  0.198150  0.229261   
maxdom   -0.305651 -0.274500 -0.324253 -0.436649  0.477187  0.519528   
dfrange  -0.304640 -0.272729 -0.319054 -0.431580  0.473775  0.515570   
modindx  -0.169325 -0.205539  0.198074  0.211477 -0.182344 -0.216979   

           meanfun    minfun    maxfun   meandom    mindom    maxdom  \
meanfreq  0.460844  0.383937  0.274004  0.536666  0.229261  0.519528   
sd       -0.466281 -0.345609 -0.129662 -0.482726 -0.357667 -0.482278   
median    0.414909  0.337602  0.251328  0.455943  0.191169  0.438919   
Q25       0.545035  0.320994  0.199841  0.467403  0.302255  0.459683   
Q75       0.155091  0.258002  0.285584  0.359181 -0.023750  0.335114   
IQR      -0.534462 -0.222680 -0.069588 -0.333362 -0.357037 -0.337877   
skew     -0.167668 -0.216954 -0.080861 -0.336848 -0.061608 -0.305651   
kurt     -0.194560 -0.203201 -0.045667 -0.303234 -0.103313 -0.274500   
sp.ent   -0.513194 -0.305826 -0.120738 -0.293562 -0.294869 -0.324253   
sfm      -0.421066 -0.362100 -0.192369 -0.428442 -0.289593 -0.436649   
mode      0.324771  0.385467  0.172329  0.491479  0.198150  0.477187   
centroid  0.460844  0.383937  0.274004  0.536666  0.229261  0.519528   
meanfun   1.000000  0.339387  0.311950  0.270840

In [ ]:
print("Total numbers of labels in the dataste : {}".format(data.shape[0]))
print("Count of male category: {}".format(data[data.label == 'male'].shape[0]))
print("Count of female category: {}".format(data[data.label == 'female'].shape[0]))

Total numbers of labels in the dataste : 3168
Count of male category: 1584
Count of female category: 1584


# Train test split

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(data.iloc[ : , : -1].values, data.iloc[ : ,  -1].values, test_size=0.2)

In [ ]:
X_train

array([[0.19016589, 0.03189056, 0.19446355, ..., 6.359375  , 6.2578125 ,
        0.13058677],
       [0.19007164, 0.06071474, 0.20991696, ..., 5.5078125 , 5.3203125 ,
        0.12595114],
       [0.21338988, 0.03687732, 0.21608018, ..., 8.8828125 , 8.859375  ,
        0.10351596],
       ...,
       [0.189245  , 0.0601139 , 0.17760243, ..., 5.109375  , 5.0859375 ,
        0.10868832],
       [0.19101377, 0.06432303, 0.21554832, ..., 4.9453125 , 4.921875  ,
        0.14372294],
       [0.19772284, 0.04348425, 0.19699192, ..., 7.        , 6.8515625 ,
        0.25863572]])

In [ ]:
from sklearn.svm import SVC
classifier1 = SVC(kernel = 'rbf')
classifier1.fit(X_train, y_train)
print('Support Vector Machine:')

print('Accuracy of SVM: {:.2f}'.format(classifier1.score(X_test,y_test)))

Support Vector Machine:
Accuracy of SVM: 0.69


# Machine Learning Models

## Using Logistic regression

In [ ]:
# importing logistic regression from scikit learn
from sklearn.linear_model import LogisticRegression

In [ ]:
# logistic regression model
log_model = LogisticRegression()

In [ ]:
# fitting the model
log_model.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [ ]:
# prediction on test data
y_predictions = log_model.predict(X_test)

### Metrics

In [ ]:
# importing metrics for evaulation of model
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score

In [ ]:
# classification report of the model
print(classification_report(y_test,y_predictions))

              precision    recall  f1-score   support

      female       0.95      0.84      0.89       328
        male       0.84      0.95      0.89       306

    accuracy                           0.89       634
   macro avg       0.90      0.89      0.89       634
weighted avg       0.90      0.89      0.89       634



In [ ]:
# confusion matrix
print("Confusion matrix : \n", confusion_matrix(y_test,y_predictions))

Confusion matrix : 
 [[274  54]
 [ 15 291]]


In [ ]:
# f1_score
from sklearn.metrics import f1_score
# f1 score metrics
f1_score_value = f1_score(y_test,y_predictions,average='weighted')
print("F1 score : ", f1_score_value)

F1 score :  0.8909875507073485


## Using Random Forest 

In [ ]:
# importing random forest
from sklearn.ensemble import RandomForestClassifier

In [ ]:
# random forest classifier
randomForestModel = RandomForestClassifier()

In [ ]:
# fitting the data into the model
randomForestModel.fit(X_train,y_train)

RandomForestClassifier()

In [ ]:
# predicting the data
predictions = randomForestModel.predict(X_test)

### Metrics

In [ ]:
# classification report of the model
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

      female       0.99      0.98      0.98       328
        male       0.98      0.99      0.98       306

    accuracy                           0.98       634
   macro avg       0.98      0.98      0.98       634
weighted avg       0.98      0.98      0.98       634



In [ ]:
print("Confusion matrix : \n",confusion_matrix(y_test,predictions))

Confusion matrix : 
 [[322   6]
 [  4 302]]


In [ ]:
# f1 score metrics of model
f1_score_value = f1_score(y_test,predictions,average='weighted')
print("F1 score : ", f1_score_value)

F1 score :  0.9842287005127341


## Using Decision Tree

In [ ]:
# importing DecisionTreeClassifier from scikit learn
from sklearn.tree import DecisionTreeClassifier

In [ ]:
# Decision Tree Model
decision_tree_model = DecisionTreeClassifier() 
decision_tree_model.fit(X_train,y_train)

# predicting the test data
y_pred = decision_tree_model.predict(X_test)

In [ ]:
# fitting the data into the model
decision_tree_model.fit(X_train,y_train)

DecisionTreeClassifier()

In [ ]:
predictions = decision_tree_model.predict(X_test)

### Metrics

In [ ]:
print("Confusion matrix : \n",confusion_matrix(y_test,predictions))

Confusion matrix : 
 [[310  18]
 [  8 298]]


In [ ]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

      female       0.97      0.95      0.96       328
        male       0.94      0.97      0.96       306

    accuracy                           0.96       634
   macro avg       0.96      0.96      0.96       634
weighted avg       0.96      0.96      0.96       634



In [ ]:
# f1 score metrics
f1_score_value = f1_score(y_test,predictions,average='weighted')
print("F1 score : ", f1_score_value)

F1 score :  0.9590027836361847
